name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: amannn/action-semantic-pull-request@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.DE_PAT }}
        # Optionally you can configure which types are allowed.
        # Default: https://github.com/commitizen/conventional-commit-types
        # with:
        #   types: fix, feat
